#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

bwrap \
  --ro-bind /usr /usr \
  --ro-bind /bin /bin \
  --ro-bind /lib /lib \
  --ro-bind /lib64 /lib64 \
  --ro-bind /etc/fonts /etc/fonts \
  --ro-bind /usr/share/ovmf /usr/share/ovmf \
  --tmpfs /tmp \
  --tmpfs ~/.cache/fontconfig \
  --bind "${SCRIPT_DIR}" /sandbox \
  --dev-bind /dev/null /dev/null \
  --proc /proc \
  --chdir /sandbox \
  make $@
